# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

array = np.random.randint(1, 21, size=(5, 5))
print("Original array: ")
print(array)

array[:, 2] = 1
print("The modified array: ")
print(array)

Original array: 
[[ 8 12  5 10 20]
 [ 9 20 14  4 12]
 [16 19 12 10 16]
 [19  9 10  3  6]
 [ 5 15 13 11 14]]
The modified array: 
[[ 8 12  1 10 20]
 [ 9 20  1  4 12]
 [16 19  1 10 16]
 [19  9  1  3  6]
 [ 5 15  1 11 14]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [7]:
array = np.arange(1, 17).reshape(4, 4)
print("Orginal array:")
print(array)

np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Orginal array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [11]:
array = np.arange(1, 37).reshape(6, 6)
print("Orginal array: ")
print(array)

print(f"The required sub-array:\n {array[2:5, 1:4]}")

Orginal array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
The required sub-array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [17]:
array = np.random.randint(1, 31, size= (5, 5))
print("The orginal array:")
print(array)

border_ele = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements: ")
print(border_ele)

The orginal array:
[[20 11 28  3 28]
 [15 12 19  8 28]
 [20 20  7 17 17]
 [18 18 16 21  8]
 [ 9  4  5 11 23]]
Border elements: 
[20 11 28  3 28  9  4  5 11 23 15 20 18 28 17  8]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [22]:
arr1 = np.random.randint(1, 21, size = (3, 4))
arr2 = np.random.randint(1, 21, size = (3, 4))
print("Array1: \n", arr1)
print("Array2: \n", arr2)
print("Addition: \n", arr1 + arr2)
print("Substraction: \n", arr1 - arr2)
print("Multiplication: \n", arr1 * arr2)
print("Division: \n", arr1 / arr2)

Array1: 
 [[ 8 20 12 15]
 [14  7  9  4]
 [ 1  4  9  9]]
Array2: 
 [[ 3  4 17  8]
 [ 7  4 18  6]
 [ 1  9  4  5]]
Addition: 
 [[11 24 29 23]
 [21 11 27 10]
 [ 2 13 13 14]]
Substraction: 
 [[ 5 16 -5  7]
 [ 7  3 -9 -2]
 [ 0 -5  5  4]]
Multiplication: 
 [[ 24  80 204 120]
 [ 98  28 162  24]
 [  1  36  36  45]]
Division: 
 [[2.66666667 5.         0.70588235 1.875     ]
 [2.         1.75       0.5        0.66666667]
 [1.         0.44444444 2.25       1.8       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [23]:
array = np.arange(1, 17).reshape((4, 4))
print("Orginal array:")
print(array)

row_sum = np.sum(array, axis = 1)
column_sum = np.sum(array, axis = 0)

print("Row-wise sum: \n", row_sum)
print("Column-wise sum: \n", column_sum)

Orginal array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum: 
 [10 26 42 58]
Column-wise sum: 
 [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [7]:
array = np.random.randint(1, 31, size = (5, 5))
print("Orginal Array: \n", array)

print("Mean: ", np.mean(array))
print("Median: ", np.median(array))
print("Std Deviation: ", np.std(array))
print("Variance: ", np.var(array))

Orginal Array: 
 [[18  4 24 25  3]
 [ 8  8 28 23 21]
 [30  8 18 15 26]
 [25 15  4 10 24]
 [ 6  5  8 20 20]]
Mean:  15.84
Median:  18.0
Std Deviation:  8.521408334307187
Variance:  72.61439999999999


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [10]:
array = np.arange(1, 10).reshape(3, 3)
print("Orginal array: \n", array)

mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array: \n", normalized_array)

Orginal array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.